# Generated by Django 4.2.1 on 2023-05-25 12:03

from django.db import migrations, models
import klass.utils


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=100, validators=[klass.utils.validate_phone_number], verbose_name='телефон'),
        ),
    ]
